version: "3.8"
services:
  app:
    build: ./core
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:app
    container_name: gg_core
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=55969362
    container_name: postgres_db