# Generated by Django 4.2.7 on 2023-11-05 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.TextField(max_length=255)),
                ("last_name", models.TextField(max_length=255)),
                ("photo", models.ImageField(upload_to="")),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                ("phone_number", models.TextField(max_length=10)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("entry_date", models.DateField(null=True)),
                ("leave_date", models.DateField(null=True)),
                ("spiritual_title", models.TextField(max_length=255)),
                ("department", models.TextField(max_length=255)),
            ],
        ),
    ]
