# Generated by Django 4.2.7 on 2023-11-06 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_student_department_alter_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
