# Generated by Django 4.2.7 on 2023-12-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_public_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spiritual_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
