# Generated by Django 4.2.7 on 2023-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_spiritual_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spiritual_title',
            field=models.CharField(choices=[('Dn', 'Deacon'), ('Kes', 'Kesis')], max_length=255, null=True),
        ),
    ]
