# Generated by Django 4.2.7 on 2023-12-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
